### ISSUE TITLE
Workflow releases

### ISSUE THREAD

**Issue by wrefgtzweve** [RaphaelIT7/gmodcommon-module-base#2]
Having a way to automatically make github releases with the generated dll files attached would be useful. Currently having to manually upload the dlls after an action is kind of clumsy while also making the dlls seem less legit as the author could've uploaded a different dll.

**Comment by RaphaelIT7** [comment]
Worked a bit on it today
[Readme](https://github.com/RaphaelIT7/gmod-common-module-base/tree/workflow?tab=readme-ov-file#release-workflow)
-> Template: [compile-release-template](https://github.com/RaphaelIT7/gmod-common-module-base/blob/workflow/.github/workflows/compile-release-template.yml)

I made it a seperate workflow because it needs the contents: write permission

**Comment by RaphaelIT7** [comment]
![image](https://github.com/user-attachments/assets/17c53c13-3e1c-492e-9d15-1fa072633bef)
So it's currently creating a draft with all the files. You should be able to freely configure it. 
Would be anything else be needed?

**Comment by wrefgtzweve** [comment]
Seems fine to me, ive been using it for this was a while since i last ran it https://github.com/wrefgtzweve/gm_icvar/blob/main/.github/workflows/compile.yml

https://github.com/wrefgtzweve/gm_icvar/releases
